### ISSUE TITLE
Raspberry pi 2 B HIGH CPU USAGE - need instructions to uninstall

### ISSUE THREAD

**Issue by c3kkos** [Honey-Pi/HoneyPi#5]
Hi, since i installed HoneyPi i have high cpu that lead to a unmanageable system, when some torrents or samba file traffic is live on network.

I simply have my raspberrypi crippled by psad AND systemd-journald.

I think processing PI's processing power is just not enough to handle HoneyPI.

I want to uninstall it, reverting HoneyPi installation, without wiping my SD card, since i've done lot of setups on it.

I keep having my systemd-journald loggin something, which i don't know how to disable.

It messed up my PiHole installation too..

This is also a warning to other users, really do make a backup copy of SD before proceding installing this.

**Comment by JavanXD** [comment]
Hi @c3kkos,
HoneyPi is not designed to run with another project such as pi-hole. It is designed to run for its own on a raspberry pi. 
Of course this does not work at all, because Pi-hole and HoneyPi each create their own web interface.
HoneyPi also changes the network settings. This is because there is an access point with a maintenance mode and HoneyPi connects to the internet with wifi or modem. 
Sorry but this is obvious. There are no uninstall instruction.

**Comment by JavanXD** [comment]
@c3kkos Please create issues only for the projects you are using. You commented the same on another "HoneyPi" repository: https://github.com/mattymcfatty/HoneyPi/issues/18

**Comment by c3kkos** [comment]
Can you leave some hints just to have pihole web interface back up? Just for temporary solution...
